apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: nginx-app
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80