apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-demo-nginx
spec:
  acme:
    email: contact@imesh.ai
    privateKeySecretRef:
      name: letsencrypt-demo-nginx-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx